name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '40 * * * *'
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: latest
          file: latest/Dockerfile
          push: true
          tags: shrutir11/rstudio-verse:latest
          
      #name: Build and Push v4.0.5
        #id: docker_build_four_zero_five
        #uses: docker/build-push-action@v2
        #with:
          #  context: 4.0.5
           # file: 4.0.5/Dockerfile
            #push: true
            #tags: shrutir11/rstudio-verse:4.0.5     
      
      #- name: Build and Push v4.0.0-ubuntu18.04
       # id: docker_build_four_zero_zero
        #uses: docker/build-push-action@v2
        #with:
         # context: 4.0.0-ubuntu18.04
          #file: 4.0.0-ubuntu18.04/Dockerfile
          #push: true
          #tags: shrutir11/rstudio-verse:4.0.0-ubuntu18.04
      
      #- name: Build and Push v3.6.3
       # id: docker_build_three_six_three
        #uses: docker/build-push-action@v1
        #with:
         # path: 3.6.3
          #Dockerfile: 3.6.3/Dockerfile
          #push: true
          #tags: 3.6.3
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
