name: Docker Image CI

on:
  push:
    branches: [ main ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          path: latest
          dockerfile: latest/Dockerfile
          push: true
          tags: shrutir11/rstudio-verse:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
